---
# vars file for docker-wordpress
docker_db_volume: /opt/{{ app }}/db_data
docker_wp_volume: /opt/{{ app }}/wp_data
docker_network: wordpress_net
db_name: db
wp_name: wordpress
wp_host_port: "{{ lookup('env','WORDPRESS_PORT') | default(8080)}}"
db_image: mysql:5.7
wp_container_port: 80
