#!/bin/ansible
---
- hosts: localhost
  vars:
    skip_backup: false # Set to true to skip archiving and uploading of player world files. 
    force_stop: false # Forces shutdown of server even if there are clients connected
    force_terminate: false # Forces a URI post event to API to terminate server.

  gather_facts: false

  tasks:

    - name: Register port 22 connections
      shell: netstat -anp | grep :22 | grep ESTABLISHED | wc -l
      register: active_port_22
      become: true

    - name: Register port 25565 connections
      shell: netstat -anp | grep :25565 | grep ESTABLISHED | wc -l
      register: active_port_25565
      become: true

    - name: set fact stopped if no active connections or force stop is true
      set_fact:
        service_state: "stopped"
      when: active_port_25565.stdout == "0" and active_port_22.stdout == "0" or force_stop == true

    - name: Send warning to players that server is stopping
      command: "{{ item }}"
      loop:
        - tmux send-keys -t minecraft 'say SERVER SHUTTING DOWN IN 10 SECONDS' ENTER
        - sleep 5
        - tmux send-keys -t minecraft 'save-all' ENTER
        - sleep 5
        - tmux send-keys -t minecraft 'say SERVER SHUTTING DOWN' ENTER
        - sleep 1
        - tmux send-keys -t minecraft 'stop' ENTER
        - sleep 5
      when: service_state == "stopped"
      become: true
      become_user: minecraft

    - name: Zip game world
      archive:
        path: /opt/minecraft/world
        dest: /opt/minecraft/world.zip
      when:
        - service_state == "stopped"
        - skip_backup == false
      become: true
      become_user: minecraft

    - name: Backup world to S3
      aws_s3:
        bucket: gamesmasko
        object: minecraft/worlds/world.zip
        src: /opt/minecraft/world.zip
        mode: put
      when:
        - service_state == "stopped"
        - skip_backup == false
      become: true
      become_user: minecraft

    - name: display ssh connections
      debug:
        var: active_port_22.stdout

    - name: display mc connections
      debug:
        var: active_port_25565.stdout

    - name: display service state
      debug:
        var: service_state
    
    - name: display force_state
      debug:
        var: force_state

    - name: Send POST to API to terminate instance
      uri:
        url: "{{ api_path }}"
        method: POST
        body_format: application/json
        body:
          - [ type, test ]
      register: uri_post
      when: active_port_25565.stdout == "0" and active_port_22.stdout == "0" or force_terminate == true